[tool.poetry]
name = "appbackend"
version = "0.1.0"
description = ""
authors = ["Ishan-Cybertowel <ishan@glemma.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
