# Generated by Django 4.2.7 on 2023-11-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendappclio', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
